server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  show-sql: true
  datasource:
#    url: jdbc:postgresql://UserDB:5432/User
    url: jdbc:postgresql://containers-us-west-164.railway.app:6485/userdb
    username: postgres
    password: Z8ue7zkFFMqz6aWsGolM
  # config:
  #   import: optional:configserver:http://localhost:8085
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      ratingHotelBreaker:
        limitRefreshPeriod: 2s
        limitForPeriod: 2
        timeoutDuration: 0s

  retry:
    instances:
      ratingHotelBreaker:
        maxAttempts: 3
        waitDuration: 2s
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      rateHotelBreakerAllUsers:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    refresh:
      enable: true
    service-url:
      defaultZone:  https://serviceregitsry-production.up.railway.app/eureka












